/********************************************************************************
** Form generated from reading UI file 'widget.ui'
**
** Created by: Qt User Interface Compiler version 5.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_WIDGET_H
#define UI_WIDGET_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDateEdit>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListView>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableView>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Widget
{
public:
    QPushButton *pushButton_min;
    QPushButton *pushButton_max;
    QPushButton *pushButton_close;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_testState;
    QLabel *label_pressure;
    QLabel *label_holdingTime;
    QPushButton *pushButton_testInterface;
    QPushButton *pushButton_testMethod;
    QPushButton *pushButton_reportQuery;
    QPushButton *pushButton_advance;
    QPushButton *pushButton_help;
    QTabWidget *tabWidget;
    QWidget *tab;
    QFrame *line_15;
    QLabel *label_19;
    QComboBox *comboBox_selCom;
    QFrame *line_16;
    QFrame *line_17;
    QFrame *line_18;
    QFrame *line_19;
    QFrame *line_20;
    QFrame *line_21;
    QFrame *line_22;
    QPushButton *pushButton_connectCom;
    QPushButton *pushButton_waterIn;
    QPushButton *pushButton_waterOff;
    QPushButton *pushButton_startStop;
    QPushButton *pushButton_pauseConti;
    QPushButton *pushButton_openCloseCamera;
    QComboBox *comboBox_selMethod;
    QTabWidget *tabWidget_testInterface;
    QWidget *tab_10;
    QLabel *label_video;
    QPushButton *pushButton_playback;
    QWidget *tab_6;
    QWidget *tab_7;
    QFrame *frame_4;
    QPushButton *pushButton_video;
    QFrame *line_24;
    QFrame *line_25;
    QFrame *line_26;
    QFrame *line_27;
    QPushButton *pushButton_curve;
    QPushButton *pushButton_report;
    QPushButton *pushButton_print;
    QLabel *label_testInterfaceMessage;
    QTextEdit *textEdit_methodInfo;
    QWidget *tab_2;
    QFrame *line_14;
    QLabel *label_methodList;
    QLabel *label_9;
    QListView *listView_methodList;
    QLabel *label_methodParams;
    QFrame *frame_2;
    QLabel *label_8;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLineEdit *lineEdit_methodName;
    QLineEdit *lineEdit_standard;
    QComboBox *comboBox_plan;
    QLineEdit *lineEdit_pressureRate;
    QLineEdit *lineEdit_setTime;
    QLineEdit *lineEdit_targetPressure;
    QLineEdit *lineEdit_pressureCycle;
    QLineEdit *lineEdit_pressureHolding;
    QTextEdit *textEdit_discription;
    QPushButton *pushButton_addMethod;
    QPushButton *pushButton_delMethod;
    QPushButton *pushButton_modifyMethod;
    QComboBox *comboBox_unit;
    QPushButton *pushButton_saveMethod;
    QLabel *label_testMethodMessage;
    QWidget *tab_3;
    QTableView *tableView_reportQuery;
    QDateEdit *dateEdit_start;
    QDateEdit *dateEdit_end;
    QLabel *label_reportQuery;
    QLabel *label_endDate;
    QLabel *label_startDate;
    QFrame *line;
    QFrame *line_2;
    QLabel *label_testMethod;
    QLabel *label_methodName;
    QLabel *label_userName;
    QComboBox *comboBox_queryTestMethod;
    QComboBox *comboBox_queryMethodName;
    QComboBox *comboBox_queryUserName;
    QFrame *line_3;
    QPushButton *pushButton_query;
    QPushButton *pushButton_delReport;
    QPushButton *pushButton_genReport;
    QLabel *label_queryMessage;
    QWidget *tab_4;
    QLabel *label_accountManagement;
    QFrame *line_4;
    QLabel *label_accountList;
    QLabel *label_accountInfo;
    QListView *listView_accountList;
    QFrame *frame;
    QLabel *label_accountName;
    QLabel *label_accountPassword;
    QLabel *label_accountType;
    QLineEdit *lineEdit_accountName;
    QLineEdit *lineEdit_accountPassword;
    QPushButton *pushButton_newAccount;
    QPushButton *pushButton_delAccount;
    QPushButton *pushButton_modifyAccount;
    QComboBox *comboBox_accountType;
    QFrame *line_10;
    QFrame *line_11;
    QLabel *label_advance;
    QLabel *label_dropRec;
    QLabel *label_flowInTime;
    QLabel *label_dropArea;
    QLabel *label_sensitivity;
    QLabel *label_ignoreWidth;
    QLabel *label_pressureRange;
    QLabel *label_centerX;
    QLabel *label_centerY;
    QLabel *label_r;
    QLineEdit *lineEdit_dropRec;
    QLineEdit *lineEdit_flowInTime;
    QLineEdit *lineEdit_dropArea;
    QLineEdit *lineEdit_sensitivity;
    QLineEdit *lineEdit_ignoreWidth;
    QLineEdit *lineEdit_pressureRange;
    QLineEdit *lineEdit_centerX;
    QLineEdit *lineEdit_centerY;
    QLineEdit *lineEdit_r;
    QFrame *line_12;
    QFrame *line_13;
    QLabel *label_pressureCali;
    QPushButton *pushButton_pressureCali;
    QLabel *label_actual1;
    QLabel *label_theory1;
    QLabel *label_actual2;
    QLabel *label_actual3;
    QLabel *label_theory2;
    QLabel *label_theory3;
    QLineEdit *lineEdit_actual1;
    QLineEdit *lineEdit_theory1;
    QLineEdit *lineEdit_actual2;
    QLineEdit *lineEdit_theory2;
    QLineEdit *lineEdit_actual3;
    QLineEdit *lineEdit_theory3;
    QPushButton *pushButton_saveAccount;
    QPushButton *pushButton_saveParams;
    QLabel *label_advanceMessage;
    QWidget *tab_5;
    QFrame *line_5;
    QFrame *line_6;
    QFrame *line_7;
    QFrame *line_8;
    QFrame *line_9;
    QLabel *label_6;
    QLabel *label_bottom;

    void setupUi(QWidget *Widget)
    {
        if (Widget->objectName().isEmpty())
            Widget->setObjectName(QStringLiteral("Widget"));
        Widget->resize(1366, 768);
        pushButton_min = new QPushButton(Widget);
        pushButton_min->setObjectName(QStringLiteral("pushButton_min"));
        pushButton_min->setGeometry(QRect(1250, 10, 29, 29));
        pushButton_min->setMinimumSize(QSize(0, 29));
        pushButton_min->setMaximumSize(QSize(29, 29));
        QIcon icon;
        icon.addFile(QStringLiteral("resource/main/min.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_min->setIcon(icon);
        pushButton_min->setIconSize(QSize(21, 21));
        pushButton_min->setFlat(true);
        pushButton_max = new QPushButton(Widget);
        pushButton_max->setObjectName(QStringLiteral("pushButton_max"));
        pushButton_max->setGeometry(QRect(1285, 10, 29, 29));
        pushButton_max->setMinimumSize(QSize(0, 29));
        pushButton_max->setMaximumSize(QSize(29, 29));
        QIcon icon1;
        icon1.addFile(QStringLiteral("resource/main/max.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_max->setIcon(icon1);
        pushButton_max->setIconSize(QSize(21, 21));
        pushButton_max->setFlat(true);
        pushButton_close = new QPushButton(Widget);
        pushButton_close->setObjectName(QStringLiteral("pushButton_close"));
        pushButton_close->setGeometry(QRect(1320, 10, 29, 29));
        pushButton_close->setMinimumSize(QSize(0, 29));
        pushButton_close->setMaximumSize(QSize(29, 29));
        QIcon icon2;
        icon2.addFile(QStringLiteral("resource/main/close.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_close->setIcon(icon2);
        pushButton_close->setIconSize(QSize(21, 21));
        pushButton_close->setFlat(true);
        label = new QLabel(Widget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(0, 0, 1366, 130));
        label->setMinimumSize(QSize(1366, 130));
        label->setPixmap(QPixmap(QString::fromUtf8("resource/main/title.png")));
        label_2 = new QLabel(Widget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(0, 0, 448, 56));
        label_2->setPixmap(QPixmap(QString::fromUtf8("resource/main/logo.png")));
        label_3 = new QLabel(Widget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(20, 70, 50, 50));
        label_3->setMinimumSize(QSize(50, 50));
        label_3->setMaximumSize(QSize(50, 50));
        label_3->setPixmap(QPixmap(QString::fromUtf8("resource/main/testState.png")));
        label_4 = new QLabel(Widget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(290, 70, 50, 50));
        label_4->setMinimumSize(QSize(50, 50));
        label_4->setMaximumSize(QSize(50, 50));
        label_4->setPixmap(QPixmap(QString::fromUtf8("resource/main/pressure.png")));
        label_5 = new QLabel(Widget);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(560, 70, 50, 50));
        label_5->setMinimumSize(QSize(50, 50));
        label_5->setMaximumSize(QSize(50, 50));
        label_5->setPixmap(QPixmap(QString::fromUtf8("resource/main/holdingTime.png")));
        label_testState = new QLabel(Widget);
        label_testState->setObjectName(QStringLiteral("label_testState"));
        label_testState->setGeometry(QRect(90, 90, 181, 20));
        label_testState->setMinimumSize(QSize(0, 20));
        QFont font;
        font.setPointSize(12);
        label_testState->setFont(font);
        label_pressure = new QLabel(Widget);
        label_pressure->setObjectName(QStringLiteral("label_pressure"));
        label_pressure->setGeometry(QRect(360, 90, 191, 20));
        label_pressure->setMinimumSize(QSize(0, 20));
        label_pressure->setFont(font);
        label_holdingTime = new QLabel(Widget);
        label_holdingTime->setObjectName(QStringLiteral("label_holdingTime"));
        label_holdingTime->setGeometry(QRect(630, 90, 231, 20));
        label_holdingTime->setMinimumSize(QSize(0, 20));
        label_holdingTime->setFont(font);
        pushButton_testInterface = new QPushButton(Widget);
        pushButton_testInterface->setObjectName(QStringLiteral("pushButton_testInterface"));
        pushButton_testInterface->setGeometry(QRect(0, 130, 273, 53));
        pushButton_testInterface->setMinimumSize(QSize(273, 53));
        pushButton_testInterface->setMaximumSize(QSize(273, 53));
        QIcon icon3;
        icon3.addFile(QStringLiteral("resource/main/testInterface.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_testInterface->setIcon(icon3);
        pushButton_testInterface->setIconSize(QSize(273, 53));
        pushButton_testInterface->setFlat(true);
        pushButton_testMethod = new QPushButton(Widget);
        pushButton_testMethod->setObjectName(QStringLiteral("pushButton_testMethod"));
        pushButton_testMethod->setGeometry(QRect(273, 130, 273, 53));
        QIcon icon4;
        icon4.addFile(QStringLiteral("resource/main/testInterface0.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_testMethod->setIcon(icon4);
        pushButton_testMethod->setIconSize(QSize(273, 53));
        pushButton_testMethod->setFlat(true);
        pushButton_reportQuery = new QPushButton(Widget);
        pushButton_reportQuery->setObjectName(QStringLiteral("pushButton_reportQuery"));
        pushButton_reportQuery->setGeometry(QRect(546, 130, 273, 53));
        QIcon icon5;
        icon5.addFile(QStringLiteral("resource/main/reportQuery0.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_reportQuery->setIcon(icon5);
        pushButton_reportQuery->setIconSize(QSize(273, 53));
        pushButton_reportQuery->setFlat(true);
        pushButton_advance = new QPushButton(Widget);
        pushButton_advance->setObjectName(QStringLiteral("pushButton_advance"));
        pushButton_advance->setGeometry(QRect(819, 130, 273, 53));
        pushButton_advance->setMinimumSize(QSize(273, 53));
        QIcon icon6;
        icon6.addFile(QStringLiteral("resource/main/advance0.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_advance->setIcon(icon6);
        pushButton_advance->setIconSize(QSize(273, 53));
        pushButton_advance->setFlat(true);
        pushButton_help = new QPushButton(Widget);
        pushButton_help->setObjectName(QStringLiteral("pushButton_help"));
        pushButton_help->setGeometry(QRect(1092, 130, 273, 53));
        QIcon icon7;
        icon7.addFile(QStringLiteral("resource/main/help0.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_help->setIcon(icon7);
        pushButton_help->setIconSize(QSize(273, 53));
        pushButton_help->setFlat(true);
        tabWidget = new QTabWidget(Widget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(6, 190, 1354, 534));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        line_15 = new QFrame(tab);
        line_15->setObjectName(QStringLiteral("line_15"));
        line_15->setGeometry(QRect(0, 34, 1355, 3));
        line_15->setFrameShape(QFrame::HLine);
        line_15->setFrameShadow(QFrame::Sunken);
        label_19 = new QLabel(tab);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(10, 5, 100, 30));
        comboBox_selCom = new QComboBox(tab);
        comboBox_selCom->setObjectName(QStringLiteral("comboBox_selCom"));
        comboBox_selCom->setGeometry(QRect(560, 5, 90, 24));
        line_16 = new QFrame(tab);
        line_16->setObjectName(QStringLiteral("line_16"));
        line_16->setGeometry(QRect(550, 5, 3, 24));
        line_16->setFrameShape(QFrame::VLine);
        line_16->setFrameShadow(QFrame::Sunken);
        line_17 = new QFrame(tab);
        line_17->setObjectName(QStringLiteral("line_17"));
        line_17->setGeometry(QRect(660, 5, 3, 24));
        line_17->setFrameShape(QFrame::VLine);
        line_17->setFrameShadow(QFrame::Sunken);
        line_18 = new QFrame(tab);
        line_18->setObjectName(QStringLiteral("line_18"));
        line_18->setGeometry(QRect(770, 5, 3, 24));
        line_18->setFrameShape(QFrame::VLine);
        line_18->setFrameShadow(QFrame::Sunken);
        line_19 = new QFrame(tab);
        line_19->setObjectName(QStringLiteral("line_19"));
        line_19->setGeometry(QRect(1100, 5, 3, 24));
        line_19->setFrameShape(QFrame::VLine);
        line_19->setFrameShadow(QFrame::Sunken);
        line_20 = new QFrame(tab);
        line_20->setObjectName(QStringLiteral("line_20"));
        line_20->setGeometry(QRect(880, 5, 3, 24));
        line_20->setFrameShape(QFrame::VLine);
        line_20->setFrameShadow(QFrame::Sunken);
        line_21 = new QFrame(tab);
        line_21->setObjectName(QStringLiteral("line_21"));
        line_21->setGeometry(QRect(990, 5, 3, 24));
        line_21->setFrameShape(QFrame::VLine);
        line_21->setFrameShadow(QFrame::Sunken);
        line_22 = new QFrame(tab);
        line_22->setObjectName(QStringLiteral("line_22"));
        line_22->setGeometry(QRect(1210, 5, 3, 24));
        line_22->setFrameShape(QFrame::VLine);
        line_22->setFrameShadow(QFrame::Sunken);
        pushButton_connectCom = new QPushButton(tab);
        pushButton_connectCom->setObjectName(QStringLiteral("pushButton_connectCom"));
        pushButton_connectCom->setGeometry(QRect(670, 5, 90, 24));
        pushButton_connectCom->setFlat(true);
        pushButton_waterIn = new QPushButton(tab);
        pushButton_waterIn->setObjectName(QStringLiteral("pushButton_waterIn"));
        pushButton_waterIn->setGeometry(QRect(780, 5, 90, 24));
        pushButton_waterIn->setFlat(true);
        pushButton_waterOff = new QPushButton(tab);
        pushButton_waterOff->setObjectName(QStringLiteral("pushButton_waterOff"));
        pushButton_waterOff->setGeometry(QRect(890, 5, 90, 24));
        pushButton_waterOff->setFlat(true);
        pushButton_startStop = new QPushButton(tab);
        pushButton_startStop->setObjectName(QStringLiteral("pushButton_startStop"));
        pushButton_startStop->setGeometry(QRect(1000, 5, 90, 24));
        pushButton_startStop->setFlat(true);
        pushButton_pauseConti = new QPushButton(tab);
        pushButton_pauseConti->setObjectName(QStringLiteral("pushButton_pauseConti"));
        pushButton_pauseConti->setGeometry(QRect(1110, 5, 90, 24));
        pushButton_pauseConti->setFlat(true);
        pushButton_openCloseCamera = new QPushButton(tab);
        pushButton_openCloseCamera->setObjectName(QStringLiteral("pushButton_openCloseCamera"));
        pushButton_openCloseCamera->setGeometry(QRect(1220, 5, 90, 24));
        pushButton_openCloseCamera->setFlat(true);
        comboBox_selMethod = new QComboBox(tab);
        comboBox_selMethod->setObjectName(QStringLiteral("comboBox_selMethod"));
        comboBox_selMethod->setGeometry(QRect(12, 45, 400, 26));
        comboBox_selMethod->setFrame(true);
        tabWidget_testInterface = new QTabWidget(tab);
        tabWidget_testInterface->setObjectName(QStringLiteral("tabWidget_testInterface"));
        tabWidget_testInterface->setGeometry(QRect(430, 71, 910, 429));
        tab_10 = new QWidget();
        tab_10->setObjectName(QStringLiteral("tab_10"));
        label_video = new QLabel(tab_10);
        label_video->setObjectName(QStringLiteral("label_video"));
        label_video->setGeometry(QRect(20, 32, 427, 342));
        label_video->setFrameShape(QFrame::StyledPanel);
        pushButton_playback = new QPushButton(tab_10);
        pushButton_playback->setObjectName(QStringLiteral("pushButton_playback"));
        pushButton_playback->setGeometry(QRect(500, 340, 240, 34));
        pushButton_playback->setFlat(false);
        tabWidget_testInterface->addTab(tab_10, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QStringLiteral("tab_6"));
        tabWidget_testInterface->addTab(tab_6, QString());
        tab_7 = new QWidget();
        tab_7->setObjectName(QStringLiteral("tab_7"));
        tabWidget_testInterface->addTab(tab_7, QString());
        frame_4 = new QFrame(tab);
        frame_4->setObjectName(QStringLiteral("frame_4"));
        frame_4->setGeometry(QRect(430, 45, 910, 26));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Plain);
        pushButton_video = new QPushButton(frame_4);
        pushButton_video->setObjectName(QStringLiteral("pushButton_video"));
        pushButton_video->setGeometry(QRect(0, 0, 56, 26));
        pushButton_video->setFlat(true);
        line_24 = new QFrame(frame_4);
        line_24->setObjectName(QStringLiteral("line_24"));
        line_24->setGeometry(QRect(57, 3, 3, 20));
        line_24->setFrameShape(QFrame::VLine);
        line_24->setFrameShadow(QFrame::Sunken);
        line_25 = new QFrame(frame_4);
        line_25->setObjectName(QStringLiteral("line_25"));
        line_25->setGeometry(QRect(116, 3, 3, 20));
        line_25->setFrameShape(QFrame::VLine);
        line_25->setFrameShadow(QFrame::Sunken);
        line_26 = new QFrame(frame_4);
        line_26->setObjectName(QStringLiteral("line_26"));
        line_26->setGeometry(QRect(175, 3, 3, 20));
        line_26->setFrameShape(QFrame::VLine);
        line_26->setFrameShadow(QFrame::Sunken);
        line_27 = new QFrame(frame_4);
        line_27->setObjectName(QStringLiteral("line_27"));
        line_27->setGeometry(QRect(234, 3, 3, 20));
        line_27->setFrameShape(QFrame::VLine);
        line_27->setFrameShadow(QFrame::Sunken);
        pushButton_curve = new QPushButton(frame_4);
        pushButton_curve->setObjectName(QStringLiteral("pushButton_curve"));
        pushButton_curve->setGeometry(QRect(59, 0, 56, 26));
        pushButton_curve->setFlat(true);
        pushButton_report = new QPushButton(frame_4);
        pushButton_report->setObjectName(QStringLiteral("pushButton_report"));
        pushButton_report->setGeometry(QRect(118, 0, 56, 26));
        pushButton_report->setFlat(true);
        pushButton_print = new QPushButton(frame_4);
        pushButton_print->setObjectName(QStringLiteral("pushButton_print"));
        pushButton_print->setGeometry(QRect(177, 0, 56, 26));
        pushButton_print->setFlat(true);
        label_testInterfaceMessage = new QLabel(tab);
        label_testInterfaceMessage->setObjectName(QStringLiteral("label_testInterfaceMessage"));
        label_testInterfaceMessage->setGeometry(QRect(120, 5, 800, 30));
        textEdit_methodInfo = new QTextEdit(tab);
        textEdit_methodInfo->setObjectName(QStringLiteral("textEdit_methodInfo"));
        textEdit_methodInfo->setGeometry(QRect(13, 70, 396, 430));
        textEdit_methodInfo->setFrameShape(QFrame::StyledPanel);
        textEdit_methodInfo->setFrameShadow(QFrame::Plain);
        tabWidget->addTab(tab, QString());
        tabWidget_testInterface->raise();
        line_15->raise();
        label_19->raise();
        comboBox_selCom->raise();
        line_16->raise();
        line_17->raise();
        line_18->raise();
        line_19->raise();
        line_20->raise();
        line_21->raise();
        line_22->raise();
        pushButton_connectCom->raise();
        pushButton_waterIn->raise();
        pushButton_waterOff->raise();
        pushButton_startStop->raise();
        pushButton_pauseConti->raise();
        pushButton_openCloseCamera->raise();
        comboBox_selMethod->raise();
        frame_4->raise();
        label_testInterfaceMessage->raise();
        textEdit_methodInfo->raise();
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        line_14 = new QFrame(tab_2);
        line_14->setObjectName(QStringLiteral("line_14"));
        line_14->setGeometry(QRect(0, 34, 1355, 3));
        line_14->setFrameShape(QFrame::HLine);
        line_14->setFrameShadow(QFrame::Sunken);
        label_methodList = new QLabel(tab_2);
        label_methodList->setObjectName(QStringLiteral("label_methodList"));
        label_methodList->setGeometry(QRect(12, 45, 460, 30));
        label_methodList->setFrameShape(QFrame::Panel);
        label_methodList->setFrameShadow(QFrame::Sunken);
        label_9 = new QLabel(tab_2);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(10, 5, 100, 30));
        listView_methodList = new QListView(tab_2);
        listView_methodList->setObjectName(QStringLiteral("listView_methodList"));
        listView_methodList->setGeometry(QRect(13, 75, 458, 420));
        listView_methodList->setFrameShape(QFrame::StyledPanel);
        listView_methodList->setFrameShadow(QFrame::Plain);
        label_methodParams = new QLabel(tab_2);
        label_methodParams->setObjectName(QStringLiteral("label_methodParams"));
        label_methodParams->setGeometry(QRect(490, 45, 846, 30));
        label_methodParams->setMinimumSize(QSize(0, 0));
        label_methodParams->setFrameShape(QFrame::Panel);
        label_methodParams->setFrameShadow(QFrame::Sunken);
        frame_2 = new QFrame(tab_2);
        frame_2->setObjectName(QStringLiteral("frame_2"));
        frame_2->setGeometry(QRect(491, 75, 845, 420));
        frame_2->setFrameShape(QFrame::Panel);
        frame_2->setFrameShadow(QFrame::Plain);
        label_8 = new QLabel(frame_2);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(20, 15, 80, 20));
        label_10 = new QLabel(frame_2);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(20, 50, 80, 30));
        label_11 = new QLabel(frame_2);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(20, 90, 80, 30));
        label_12 = new QLabel(frame_2);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(20, 130, 80, 30));
        label_13 = new QLabel(frame_2);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(20, 170, 80, 30));
        label_14 = new QLabel(frame_2);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(400, 10, 80, 30));
        label_15 = new QLabel(frame_2);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(400, 50, 80, 30));
        label_16 = new QLabel(frame_2);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(400, 90, 80, 30));
        label_17 = new QLabel(frame_2);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(400, 130, 80, 30));
        label_18 = new QLabel(frame_2);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(20, 214, 80, 30));
        lineEdit_methodName = new QLineEdit(frame_2);
        lineEdit_methodName->setObjectName(QStringLiteral("lineEdit_methodName"));
        lineEdit_methodName->setEnabled(false);
        lineEdit_methodName->setGeometry(QRect(90, 10, 270, 30));
        lineEdit_standard = new QLineEdit(frame_2);
        lineEdit_standard->setObjectName(QStringLiteral("lineEdit_standard"));
        lineEdit_standard->setEnabled(false);
        lineEdit_standard->setGeometry(QRect(90, 90, 270, 30));
        comboBox_plan = new QComboBox(frame_2);
        comboBox_plan->setObjectName(QStringLiteral("comboBox_plan"));
        comboBox_plan->setEnabled(false);
        comboBox_plan->setGeometry(QRect(90, 50, 270, 30));
        lineEdit_pressureRate = new QLineEdit(frame_2);
        lineEdit_pressureRate->setObjectName(QStringLiteral("lineEdit_pressureRate"));
        lineEdit_pressureRate->setEnabled(false);
        lineEdit_pressureRate->setGeometry(QRect(90, 130, 270, 30));
        lineEdit_setTime = new QLineEdit(frame_2);
        lineEdit_setTime->setObjectName(QStringLiteral("lineEdit_setTime"));
        lineEdit_setTime->setEnabled(false);
        lineEdit_setTime->setGeometry(QRect(90, 170, 270, 30));
        lineEdit_targetPressure = new QLineEdit(frame_2);
        lineEdit_targetPressure->setObjectName(QStringLiteral("lineEdit_targetPressure"));
        lineEdit_targetPressure->setEnabled(false);
        lineEdit_targetPressure->setGeometry(QRect(470, 10, 270, 30));
        lineEdit_pressureCycle = new QLineEdit(frame_2);
        lineEdit_pressureCycle->setObjectName(QStringLiteral("lineEdit_pressureCycle"));
        lineEdit_pressureCycle->setEnabled(false);
        lineEdit_pressureCycle->setGeometry(QRect(470, 50, 270, 30));
        lineEdit_pressureHolding = new QLineEdit(frame_2);
        lineEdit_pressureHolding->setObjectName(QStringLiteral("lineEdit_pressureHolding"));
        lineEdit_pressureHolding->setEnabled(false);
        lineEdit_pressureHolding->setGeometry(QRect(470, 90, 270, 30));
        textEdit_discription = new QTextEdit(frame_2);
        textEdit_discription->setObjectName(QStringLiteral("textEdit_discription"));
        textEdit_discription->setEnabled(false);
        textEdit_discription->setGeometry(QRect(90, 214, 652, 148));
        pushButton_addMethod = new QPushButton(frame_2);
        pushButton_addMethod->setObjectName(QStringLiteral("pushButton_addMethod"));
        pushButton_addMethod->setGeometry(QRect(20, 372, 189, 38));
        pushButton_delMethod = new QPushButton(frame_2);
        pushButton_delMethod->setObjectName(QStringLiteral("pushButton_delMethod"));
        pushButton_delMethod->setGeometry(QRect(217, 372, 189, 38));
        pushButton_modifyMethod = new QPushButton(frame_2);
        pushButton_modifyMethod->setObjectName(QStringLiteral("pushButton_modifyMethod"));
        pushButton_modifyMethod->setGeometry(QRect(416, 372, 189, 38));
        comboBox_unit = new QComboBox(frame_2);
        comboBox_unit->setObjectName(QStringLiteral("comboBox_unit"));
        comboBox_unit->setEnabled(true);
        comboBox_unit->setGeometry(QRect(470, 130, 270, 30));
        pushButton_saveMethod = new QPushButton(tab_2);
        pushButton_saveMethod->setObjectName(QStringLiteral("pushButton_saveMethod"));
        pushButton_saveMethod->setGeometry(QRect(1305, 54, 15, 15));
        QIcon icon8;
        icon8.addFile(QStringLiteral("resource/testmethod/methodSave.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_saveMethod->setIcon(icon8);
        pushButton_saveMethod->setFlat(true);
        label_testMethodMessage = new QLabel(tab_2);
        label_testMethodMessage->setObjectName(QStringLiteral("label_testMethodMessage"));
        label_testMethodMessage->setGeometry(QRect(120, 5, 1000, 30));
        tabWidget->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        tableView_reportQuery = new QTableView(tab_3);
        tableView_reportQuery->setObjectName(QStringLiteral("tableView_reportQuery"));
        tableView_reportQuery->setGeometry(QRect(9, 45, 1330, 270));
        tableView_reportQuery->setFrameShape(QFrame::StyledPanel);
        tableView_reportQuery->setFrameShadow(QFrame::Plain);
        tableView_reportQuery->setLineWidth(1);
        tableView_reportQuery->setShowGrid(true);
        tableView_reportQuery->setGridStyle(Qt::SolidLine);
        dateEdit_start = new QDateEdit(tab_3);
        dateEdit_start->setObjectName(QStringLiteral("dateEdit_start"));
        dateEdit_start->setGeometry(QRect(100, 352, 242, 30));
        dateEdit_start->setMinimumSize(QSize(242, 30));
        dateEdit_start->setMaximumSize(QSize(242, 30));
        dateEdit_end = new QDateEdit(tab_3);
        dateEdit_end->setObjectName(QStringLiteral("dateEdit_end"));
        dateEdit_end->setGeometry(QRect(100, 396, 242, 30));
        dateEdit_end->setMinimumSize(QSize(242, 30));
        dateEdit_end->setMaximumSize(QSize(242, 30));
        label_reportQuery = new QLabel(tab_3);
        label_reportQuery->setObjectName(QStringLiteral("label_reportQuery"));
        label_reportQuery->setGeometry(QRect(10, 5, 120, 30));
        label_reportQuery->setMinimumSize(QSize(120, 30));
        label_reportQuery->setMaximumSize(QSize(16777215, 30));
        QFont font1;
        font1.setPointSize(9);
        label_reportQuery->setFont(font1);
        label_endDate = new QLabel(tab_3);
        label_endDate->setObjectName(QStringLiteral("label_endDate"));
        label_endDate->setGeometry(QRect(14, 396, 100, 30));
        label_endDate->setMinimumSize(QSize(30, 30));
        label_endDate->setFont(font1);
        label_startDate = new QLabel(tab_3);
        label_startDate->setObjectName(QStringLiteral("label_startDate"));
        label_startDate->setGeometry(QRect(14, 352, 100, 30));
        label_startDate->setMinimumSize(QSize(30, 30));
        label_startDate->setFont(font1);
        line = new QFrame(tab_3);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(0, 34, 1366, 3));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(tab_3);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(0, 336, 1366, 3));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        label_testMethod = new QLabel(tab_3);
        label_testMethod->setObjectName(QStringLiteral("label_testMethod"));
        label_testMethod->setGeometry(QRect(434, 352, 100, 30));
        label_testMethod->setMinimumSize(QSize(30, 30));
        label_testMethod->setFont(font1);
        label_methodName = new QLabel(tab_3);
        label_methodName->setObjectName(QStringLiteral("label_methodName"));
        label_methodName->setGeometry(QRect(434, 396, 100, 30));
        label_methodName->setMinimumSize(QSize(30, 30));
        label_methodName->setFont(font1);
        label_userName = new QLabel(tab_3);
        label_userName->setObjectName(QStringLiteral("label_userName"));
        label_userName->setGeometry(QRect(854, 352, 60, 30));
        label_userName->setMinimumSize(QSize(30, 30));
        label_userName->setFont(font1);
        comboBox_queryTestMethod = new QComboBox(tab_3);
        comboBox_queryTestMethod->setObjectName(QStringLiteral("comboBox_queryTestMethod"));
        comboBox_queryTestMethod->setGeometry(QRect(520, 352, 242, 30));
        comboBox_queryTestMethod->setMinimumSize(QSize(30, 0));
        comboBox_queryMethodName = new QComboBox(tab_3);
        comboBox_queryMethodName->setObjectName(QStringLiteral("comboBox_queryMethodName"));
        comboBox_queryMethodName->setGeometry(QRect(520, 396, 242, 30));
        comboBox_queryMethodName->setMinimumSize(QSize(30, 0));
        comboBox_queryUserName = new QComboBox(tab_3);
        comboBox_queryUserName->setObjectName(QStringLiteral("comboBox_queryUserName"));
        comboBox_queryUserName->setGeometry(QRect(905, 352, 242, 30));
        comboBox_queryUserName->setMinimumSize(QSize(30, 0));
        line_3 = new QFrame(tab_3);
        line_3->setObjectName(QStringLiteral("line_3"));
        line_3->setGeometry(QRect(0, 440, 1366, 3));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        pushButton_query = new QPushButton(tab_3);
        pushButton_query->setObjectName(QStringLiteral("pushButton_query"));
        pushButton_query->setGeometry(QRect(14, 465, 320, 34));
        pushButton_query->setMinimumSize(QSize(0, 34));
        pushButton_query->setFont(font1);
        pushButton_delReport = new QPushButton(tab_3);
        pushButton_delReport->setObjectName(QStringLiteral("pushButton_delReport"));
        pushButton_delReport->setGeometry(QRect(350, 465, 320, 34));
        pushButton_delReport->setMinimumSize(QSize(0, 34));
        pushButton_delReport->setFont(font1);
        pushButton_genReport = new QPushButton(tab_3);
        pushButton_genReport->setObjectName(QStringLiteral("pushButton_genReport"));
        pushButton_genReport->setGeometry(QRect(686, 465, 320, 34));
        pushButton_genReport->setMinimumSize(QSize(0, 34));
        pushButton_genReport->setFont(font1);
        label_queryMessage = new QLabel(tab_3);
        label_queryMessage->setObjectName(QStringLiteral("label_queryMessage"));
        label_queryMessage->setGeometry(QRect(120, 5, 1000, 30));
        tabWidget->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        label_accountManagement = new QLabel(tab_4);
        label_accountManagement->setObjectName(QStringLiteral("label_accountManagement"));
        label_accountManagement->setGeometry(QRect(10, 5, 100, 30));
        label_accountManagement->setFont(font1);
        line_4 = new QFrame(tab_4);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setGeometry(QRect(0, 34, 1354, 3));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        label_accountList = new QLabel(tab_4);
        label_accountList->setObjectName(QStringLiteral("label_accountList"));
        label_accountList->setGeometry(QRect(12, 45, 422, 30));
        label_accountList->setFont(font1);
        label_accountList->setFrameShape(QFrame::Panel);
        label_accountList->setFrameShadow(QFrame::Sunken);
        label_accountInfo = new QLabel(tab_4);
        label_accountInfo->setObjectName(QStringLiteral("label_accountInfo"));
        label_accountInfo->setGeometry(QRect(448, 45, 886, 30));
        label_accountInfo->setMinimumSize(QSize(884, 30));
        label_accountInfo->setMaximumSize(QSize(2000, 30));
        label_accountInfo->setFont(font1);
        label_accountInfo->setFrameShape(QFrame::Panel);
        label_accountInfo->setFrameShadow(QFrame::Sunken);
        label_accountInfo->setLineWidth(1);
        listView_accountList = new QListView(tab_4);
        listView_accountList->setObjectName(QStringLiteral("listView_accountList"));
        listView_accountList->setGeometry(QRect(13, 75, 420, 135));
        listView_accountList->setFrameShape(QFrame::StyledPanel);
        listView_accountList->setFrameShadow(QFrame::Plain);
        frame = new QFrame(tab_4);
        frame->setObjectName(QStringLiteral("frame"));
        frame->setGeometry(QRect(449, 75, 884, 135));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Plain);
        label_accountName = new QLabel(frame);
        label_accountName->setObjectName(QStringLiteral("label_accountName"));
        label_accountName->setGeometry(QRect(34, 10, 80, 30));
        label_accountName->setFont(font1);
        label_accountName->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_accountPassword = new QLabel(frame);
        label_accountPassword->setObjectName(QStringLiteral("label_accountPassword"));
        label_accountPassword->setGeometry(QRect(34, 50, 80, 30));
        label_accountPassword->setFont(font1);
        label_accountPassword->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_accountType = new QLabel(frame);
        label_accountType->setObjectName(QStringLiteral("label_accountType"));
        label_accountType->setGeometry(QRect(490, 10, 90, 30));
        label_accountType->setFont(font1);
        lineEdit_accountName = new QLineEdit(frame);
        lineEdit_accountName->setObjectName(QStringLiteral("lineEdit_accountName"));
        lineEdit_accountName->setEnabled(false);
        lineEdit_accountName->setGeometry(QRect(124, 10, 242, 30));
        lineEdit_accountPassword = new QLineEdit(frame);
        lineEdit_accountPassword->setObjectName(QStringLiteral("lineEdit_accountPassword"));
        lineEdit_accountPassword->setEnabled(false);
        lineEdit_accountPassword->setGeometry(QRect(124, 50, 242, 30));
        pushButton_newAccount = new QPushButton(frame);
        pushButton_newAccount->setObjectName(QStringLiteral("pushButton_newAccount"));
        pushButton_newAccount->setGeometry(QRect(34, 85, 186, 34));
        pushButton_delAccount = new QPushButton(frame);
        pushButton_delAccount->setObjectName(QStringLiteral("pushButton_delAccount"));
        pushButton_delAccount->setGeometry(QRect(228, 85, 186, 34));
        pushButton_modifyAccount = new QPushButton(frame);
        pushButton_modifyAccount->setObjectName(QStringLiteral("pushButton_modifyAccount"));
        pushButton_modifyAccount->setGeometry(QRect(422, 85, 186, 34));
        comboBox_accountType = new QComboBox(frame);
        comboBox_accountType->setObjectName(QStringLiteral("comboBox_accountType"));
        comboBox_accountType->setEnabled(false);
        comboBox_accountType->setGeometry(QRect(570, 10, 242, 30));
        comboBox_accountType->setMinimumSize(QSize(30, 0));
        line_10 = new QFrame(tab_4);
        line_10->setObjectName(QStringLiteral("line_10"));
        line_10->setGeometry(QRect(0, 220, 1354, 3));
        line_10->setFrameShape(QFrame::HLine);
        line_10->setFrameShadow(QFrame::Sunken);
        line_11 = new QFrame(tab_4);
        line_11->setObjectName(QStringLiteral("line_11"));
        line_11->setGeometry(QRect(0, 250, 1354, 3));
        line_11->setFrameShape(QFrame::HLine);
        line_11->setFrameShadow(QFrame::Sunken);
        label_advance = new QLabel(tab_4);
        label_advance->setObjectName(QStringLiteral("label_advance"));
        label_advance->setGeometry(QRect(12, 220, 80, 30));
        label_advance->setFont(font1);
        label_dropRec = new QLabel(tab_4);
        label_dropRec->setObjectName(QStringLiteral("label_dropRec"));
        label_dropRec->setGeometry(QRect(20, 260, 90, 30));
        label_dropRec->setFont(font1);
        label_flowInTime = new QLabel(tab_4);
        label_flowInTime->setObjectName(QStringLiteral("label_flowInTime"));
        label_flowInTime->setGeometry(QRect(20, 300, 90, 31));
        label_flowInTime->setFont(font1);
        label_dropArea = new QLabel(tab_4);
        label_dropArea->setObjectName(QStringLiteral("label_dropArea"));
        label_dropArea->setGeometry(QRect(20, 340, 90, 30));
        label_dropArea->setFont(font1);
        label_sensitivity = new QLabel(tab_4);
        label_sensitivity->setObjectName(QStringLiteral("label_sensitivity"));
        label_sensitivity->setGeometry(QRect(468, 260, 130, 30));
        label_sensitivity->setFont(font1);
        label_sensitivity->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_ignoreWidth = new QLabel(tab_4);
        label_ignoreWidth->setObjectName(QStringLiteral("label_ignoreWidth"));
        label_ignoreWidth->setGeometry(QRect(468, 300, 130, 30));
        label_ignoreWidth->setFont(font1);
        label_ignoreWidth->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_pressureRange = new QLabel(tab_4);
        label_pressureRange->setObjectName(QStringLiteral("label_pressureRange"));
        label_pressureRange->setGeometry(QRect(468, 339, 130, 30));
        label_pressureRange->setFont(font1);
        label_pressureRange->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_centerX = new QLabel(tab_4);
        label_centerX->setObjectName(QStringLiteral("label_centerX"));
        label_centerX->setGeometry(QRect(970, 260, 110, 30));
        label_centerX->setFont(font1);
        label_centerX->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_centerY = new QLabel(tab_4);
        label_centerY->setObjectName(QStringLiteral("label_centerY"));
        label_centerY->setGeometry(QRect(970, 300, 110, 30));
        label_centerY->setFont(font1);
        label_centerY->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_r = new QLabel(tab_4);
        label_r->setObjectName(QStringLiteral("label_r"));
        label_r->setGeometry(QRect(970, 339, 110, 30));
        label_r->setFont(font1);
        label_r->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_dropRec = new QLineEdit(tab_4);
        lineEdit_dropRec->setObjectName(QStringLiteral("lineEdit_dropRec"));
        lineEdit_dropRec->setEnabled(false);
        lineEdit_dropRec->setGeometry(QRect(110, 260, 242, 30));
        lineEdit_flowInTime = new QLineEdit(tab_4);
        lineEdit_flowInTime->setObjectName(QStringLiteral("lineEdit_flowInTime"));
        lineEdit_flowInTime->setEnabled(false);
        lineEdit_flowInTime->setGeometry(QRect(110, 300, 242, 30));
        lineEdit_dropArea = new QLineEdit(tab_4);
        lineEdit_dropArea->setObjectName(QStringLiteral("lineEdit_dropArea"));
        lineEdit_dropArea->setEnabled(false);
        lineEdit_dropArea->setGeometry(QRect(110, 340, 242, 30));
        lineEdit_sensitivity = new QLineEdit(tab_4);
        lineEdit_sensitivity->setObjectName(QStringLiteral("lineEdit_sensitivity"));
        lineEdit_sensitivity->setEnabled(false);
        lineEdit_sensitivity->setGeometry(QRect(608, 260, 242, 30));
        lineEdit_ignoreWidth = new QLineEdit(tab_4);
        lineEdit_ignoreWidth->setObjectName(QStringLiteral("lineEdit_ignoreWidth"));
        lineEdit_ignoreWidth->setEnabled(false);
        lineEdit_ignoreWidth->setGeometry(QRect(608, 300, 242, 30));
        lineEdit_pressureRange = new QLineEdit(tab_4);
        lineEdit_pressureRange->setObjectName(QStringLiteral("lineEdit_pressureRange"));
        lineEdit_pressureRange->setEnabled(false);
        lineEdit_pressureRange->setGeometry(QRect(608, 339, 242, 30));
        lineEdit_centerX = new QLineEdit(tab_4);
        lineEdit_centerX->setObjectName(QStringLiteral("lineEdit_centerX"));
        lineEdit_centerX->setEnabled(false);
        lineEdit_centerX->setGeometry(QRect(1090, 260, 242, 30));
        lineEdit_centerY = new QLineEdit(tab_4);
        lineEdit_centerY->setObjectName(QStringLiteral("lineEdit_centerY"));
        lineEdit_centerY->setEnabled(false);
        lineEdit_centerY->setGeometry(QRect(1090, 300, 242, 30));
        lineEdit_r = new QLineEdit(tab_4);
        lineEdit_r->setObjectName(QStringLiteral("lineEdit_r"));
        lineEdit_r->setEnabled(false);
        lineEdit_r->setGeometry(QRect(1090, 339, 242, 30));
        line_12 = new QFrame(tab_4);
        line_12->setObjectName(QStringLiteral("line_12"));
        line_12->setGeometry(QRect(0, 390, 1354, 3));
        line_12->setFrameShape(QFrame::HLine);
        line_12->setFrameShadow(QFrame::Sunken);
        line_13 = new QFrame(tab_4);
        line_13->setObjectName(QStringLiteral("line_13"));
        line_13->setGeometry(QRect(0, 420, 1354, 3));
        line_13->setFrameShape(QFrame::HLine);
        line_13->setFrameShadow(QFrame::Sunken);
        label_pressureCali = new QLabel(tab_4);
        label_pressureCali->setObjectName(QStringLiteral("label_pressureCali"));
        label_pressureCali->setGeometry(QRect(12, 390, 80, 30));
        label_pressureCali->setFont(font1);
        pushButton_pressureCali = new QPushButton(tab_4);
        pushButton_pressureCali->setObjectName(QStringLiteral("pushButton_pressureCali"));
        pushButton_pressureCali->setGeometry(QRect(1260, 392, 83, 27));
        pushButton_pressureCali->setFont(font1);
        pushButton_pressureCali->setFlat(true);
        label_actual1 = new QLabel(tab_4);
        label_actual1->setObjectName(QStringLiteral("label_actual1"));
        label_actual1->setGeometry(QRect(30, 430, 80, 30));
        label_actual1->setFont(font1);
        label_theory1 = new QLabel(tab_4);
        label_theory1->setObjectName(QStringLiteral("label_theory1"));
        label_theory1->setGeometry(QRect(30, 475, 80, 30));
        label_theory1->setFont(font1);
        label_actual2 = new QLabel(tab_4);
        label_actual2->setObjectName(QStringLiteral("label_actual2"));
        label_actual2->setGeometry(QRect(518, 430, 80, 30));
        label_actual2->setFont(font1);
        label_actual3 = new QLabel(tab_4);
        label_actual3->setObjectName(QStringLiteral("label_actual3"));
        label_actual3->setGeometry(QRect(1010, 430, 80, 30));
        label_actual3->setFont(font1);
        label_theory2 = new QLabel(tab_4);
        label_theory2->setObjectName(QStringLiteral("label_theory2"));
        label_theory2->setGeometry(QRect(518, 475, 80, 30));
        label_theory2->setFont(font1);
        label_theory3 = new QLabel(tab_4);
        label_theory3->setObjectName(QStringLiteral("label_theory3"));
        label_theory3->setGeometry(QRect(1010, 475, 80, 30));
        label_theory3->setFont(font1);
        lineEdit_actual1 = new QLineEdit(tab_4);
        lineEdit_actual1->setObjectName(QStringLiteral("lineEdit_actual1"));
        lineEdit_actual1->setEnabled(false);
        lineEdit_actual1->setGeometry(QRect(110, 430, 242, 30));
        lineEdit_theory1 = new QLineEdit(tab_4);
        lineEdit_theory1->setObjectName(QStringLiteral("lineEdit_theory1"));
        lineEdit_theory1->setEnabled(false);
        lineEdit_theory1->setGeometry(QRect(110, 475, 242, 30));
        lineEdit_actual2 = new QLineEdit(tab_4);
        lineEdit_actual2->setObjectName(QStringLiteral("lineEdit_actual2"));
        lineEdit_actual2->setEnabled(false);
        lineEdit_actual2->setGeometry(QRect(608, 430, 242, 30));
        lineEdit_theory2 = new QLineEdit(tab_4);
        lineEdit_theory2->setObjectName(QStringLiteral("lineEdit_theory2"));
        lineEdit_theory2->setEnabled(false);
        lineEdit_theory2->setGeometry(QRect(608, 475, 242, 30));
        lineEdit_actual3 = new QLineEdit(tab_4);
        lineEdit_actual3->setObjectName(QStringLiteral("lineEdit_actual3"));
        lineEdit_actual3->setEnabled(false);
        lineEdit_actual3->setGeometry(QRect(1090, 430, 242, 30));
        lineEdit_theory3 = new QLineEdit(tab_4);
        lineEdit_theory3->setObjectName(QStringLiteral("lineEdit_theory3"));
        lineEdit_theory3->setEnabled(false);
        lineEdit_theory3->setGeometry(QRect(1090, 475, 242, 30));
        pushButton_saveAccount = new QPushButton(tab_4);
        pushButton_saveAccount->setObjectName(QStringLiteral("pushButton_saveAccount"));
        pushButton_saveAccount->setGeometry(QRect(1310, 53, 15, 15));
        QIcon icon9;
        icon9.addFile(QStringLiteral("resource/advance/advanceSave0.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_saveAccount->setIcon(icon9);
        pushButton_saveAccount->setFlat(true);
        pushButton_saveParams = new QPushButton(tab_4);
        pushButton_saveParams->setObjectName(QStringLiteral("pushButton_saveParams"));
        pushButton_saveParams->setGeometry(QRect(1310, 228, 15, 15));
        QIcon icon10;
        icon10.addFile(QStringLiteral("resource/advance/advanceSave1.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_saveParams->setIcon(icon10);
        label_advanceMessage = new QLabel(tab_4);
        label_advanceMessage->setObjectName(QStringLiteral("label_advanceMessage"));
        label_advanceMessage->setGeometry(QRect(120, 5, 1000, 30));
        tabWidget->addTab(tab_4, QString());
        label_accountManagement->raise();
        line_4->raise();
        listView_accountList->raise();
        frame->raise();
        label_accountList->raise();
        line_10->raise();
        line_11->raise();
        label_advance->raise();
        label_accountInfo->raise();
        label_dropRec->raise();
        label_flowInTime->raise();
        label_dropArea->raise();
        label_sensitivity->raise();
        label_ignoreWidth->raise();
        label_pressureRange->raise();
        label_centerX->raise();
        label_centerY->raise();
        label_r->raise();
        lineEdit_dropRec->raise();
        lineEdit_flowInTime->raise();
        lineEdit_dropArea->raise();
        lineEdit_sensitivity->raise();
        lineEdit_ignoreWidth->raise();
        lineEdit_pressureRange->raise();
        lineEdit_centerX->raise();
        lineEdit_centerY->raise();
        lineEdit_r->raise();
        line_12->raise();
        line_13->raise();
        label_pressureCali->raise();
        pushButton_pressureCali->raise();
        label_actual1->raise();
        label_theory1->raise();
        label_actual2->raise();
        label_actual3->raise();
        label_theory2->raise();
        label_theory3->raise();
        lineEdit_actual1->raise();
        lineEdit_theory1->raise();
        lineEdit_actual2->raise();
        lineEdit_theory2->raise();
        lineEdit_actual3->raise();
        lineEdit_theory3->raise();
        pushButton_saveAccount->raise();
        pushButton_saveParams->raise();
        label_advanceMessage->raise();
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        tabWidget->addTab(tab_5, QString());
        line_5 = new QFrame(Widget);
        line_5->setObjectName(QStringLiteral("line_5"));
        line_5->setGeometry(QRect(273, 130, 3, 52));
        line_5->setFrameShape(QFrame::VLine);
        line_5->setFrameShadow(QFrame::Sunken);
        line_6 = new QFrame(Widget);
        line_6->setObjectName(QStringLiteral("line_6"));
        line_6->setGeometry(QRect(546, 130, 3, 52));
        line_6->setFrameShape(QFrame::VLine);
        line_6->setFrameShadow(QFrame::Sunken);
        line_7 = new QFrame(Widget);
        line_7->setObjectName(QStringLiteral("line_7"));
        line_7->setGeometry(QRect(819, 130, 3, 52));
        line_7->setFrameShape(QFrame::VLine);
        line_7->setFrameShadow(QFrame::Sunken);
        line_8 = new QFrame(Widget);
        line_8->setObjectName(QStringLiteral("line_8"));
        line_8->setGeometry(QRect(1089, 130, 3, 52));
        line_8->setFrameShape(QFrame::VLine);
        line_8->setFrameShadow(QFrame::Sunken);
        line_9 = new QFrame(Widget);
        line_9->setObjectName(QStringLiteral("line_9"));
        line_9->setGeometry(QRect(0, 183, 1366, 3));
        line_9->setFrameShape(QFrame::HLine);
        line_9->setFrameShadow(QFrame::Sunken);
        label_6 = new QLabel(Widget);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(2, 735, 1360, 30));
        label_6->setPixmap(QPixmap(QString::fromUtf8("resource/main/bottom.png")));
        label_bottom = new QLabel(Widget);
        label_bottom->setObjectName(QStringLiteral("label_bottom"));
        label_bottom->setGeometry(QRect(1090, 738, 261, 20));
        QFont font2;
        font2.setPointSize(7);
        label_bottom->setFont(font2);
        label->raise();
        pushButton_min->raise();
        pushButton_max->raise();
        pushButton_close->raise();
        label_2->raise();
        label_3->raise();
        label_4->raise();
        label_5->raise();
        label_testState->raise();
        label_pressure->raise();
        label_holdingTime->raise();
        pushButton_testInterface->raise();
        pushButton_testMethod->raise();
        pushButton_advance->raise();
        pushButton_help->raise();
        line_5->raise();
        line_7->raise();
        line_8->raise();
        line_9->raise();
        pushButton_reportQuery->raise();
        line_6->raise();
        tabWidget->raise();
        label_6->raise();
        label_bottom->raise();

        retranslateUi(Widget);

        tabWidget->setCurrentIndex(2);
        tabWidget_testInterface->setCurrentIndex(2);


        QMetaObject::connectSlotsByName(Widget);
    } // setupUi

    void retranslateUi(QWidget *Widget)
    {
        Widget->setWindowTitle(QApplication::translate("Widget", "Widget", 0));
        pushButton_min->setText(QString());
        pushButton_max->setText(QString());
        pushButton_close->setText(QString());
        label->setText(QString());
        label_2->setText(QString());
        label_3->setText(QString());
        label_4->setText(QString());
        label_5->setText(QString());
        label_testState->setText(QApplication::translate("Widget", "\346\265\213\350\257\225\347\212\266\346\200\201", 0));
        label_pressure->setText(QApplication::translate("Widget", "\345\216\213\345\212\233", 0));
        label_holdingTime->setText(QApplication::translate("Widget", "\346\265\213\350\257\225\346\227\266\351\227\264", 0));
        pushButton_testInterface->setText(QString());
        pushButton_testMethod->setText(QString());
        pushButton_reportQuery->setText(QString());
        pushButton_advance->setText(QString());
        pushButton_help->setText(QString());
        label_19->setText(QApplication::translate("Widget", "\346\265\213\350\257\225\345\233\276\350\241\250", 0));
        pushButton_connectCom->setText(QApplication::translate("Widget", "\350\201\224\346\234\272", 0));
        pushButton_waterIn->setText(QApplication::translate("Widget", "\350\277\233\346\260\264", 0));
        pushButton_waterOff->setText(QApplication::translate("Widget", "\346\216\222\346\260\264", 0));
        pushButton_startStop->setText(QApplication::translate("Widget", "\345\274\200\345\247\213", 0));
        pushButton_pauseConti->setText(QApplication::translate("Widget", "\346\232\202\345\201\234", 0));
        pushButton_openCloseCamera->setText(QApplication::translate("Widget", "\346\211\223\345\274\200\347\233\270\346\234\272", 0));
        comboBox_selMethod->clear();
        comboBox_selMethod->insertItems(0, QStringList()
         << QApplication::translate("Widget", "\350\257\267\351\200\211\346\213\251\346\265\213\350\257\225\346\226\271\346\263\225", 0)
        );
        label_video->setText(QString());
        pushButton_playback->setText(QApplication::translate("Widget", "\350\247\206\351\242\221\345\233\236\346\224\276", 0));
        tabWidget_testInterface->setTabText(tabWidget_testInterface->indexOf(tab_10), QApplication::translate("Widget", "\345\233\276\350\241\250", 0));
        tabWidget_testInterface->setTabText(tabWidget_testInterface->indexOf(tab_6), QApplication::translate("Widget", "\346\233\262\347\272\277", 0));
        tabWidget_testInterface->setTabText(tabWidget_testInterface->indexOf(tab_7), QApplication::translate("Widget", "\346\212\245\345\221\212", 0));
        pushButton_video->setText(QApplication::translate("Widget", "\345\233\276\350\241\250", 0));
        pushButton_curve->setText(QApplication::translate("Widget", "\346\233\262\347\272\277", 0));
        pushButton_report->setText(QApplication::translate("Widget", "\346\212\245\345\221\212", 0));
        pushButton_print->setText(QApplication::translate("Widget", "\346\211\223\345\215\260", 0));
        label_testInterfaceMessage->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("Widget", "Tab 1", 0));
        label_methodList->setText(QApplication::translate("Widget", "\346\243\200\346\265\213\346\226\271\346\263\225\345\210\227\350\241\250", 0));
        label_9->setText(QApplication::translate("Widget", "\346\243\200\346\265\213\346\226\271\346\263\225", 0));
        label_methodParams->setText(QApplication::translate("Widget", "\346\226\271\346\263\225\345\217\202\346\225\260", 0));
        label_8->setText(QApplication::translate("Widget", "\346\226\271\346\263\225\345\220\215\347\247\260\357\274\232", 0));
        label_10->setText(QApplication::translate("Widget", "\346\265\213\350\257\225\346\226\271\346\241\210\357\274\232", 0));
        label_11->setText(QApplication::translate("Widget", "\345\274\225\347\224\250\346\240\207\345\207\206\357\274\232", 0));
        label_12->setText(QApplication::translate("Widget", "\345\242\236\345\216\213\351\200\237\347\216\207\357\274\232", 0));
        label_13->setText(QApplication::translate("Widget", "\345\256\232\346\227\266\346\227\266\351\227\264\357\274\232", 0));
        label_14->setText(QApplication::translate("Widget", "\347\233\256\346\240\207\345\216\213\345\274\272\357\274\232", 0));
        label_15->setText(QApplication::translate("Widget", "\346\235\276\347\273\225\345\221\250\346\234\237\357\274\232", 0));
        label_16->setText(QApplication::translate("Widget", "\344\277\235\345\216\213\346\227\266\351\227\264\357\274\232", 0));
        label_17->setText(QApplication::translate("Widget", "\345\216\213\345\212\233\345\215\225\344\275\215\357\274\232", 0));
        label_18->setText(QApplication::translate("Widget", "\346\217\217\350\277\260\357\274\232", 0));
        comboBox_plan->clear();
        comboBox_plan->insertItems(0, QStringList()
         << QApplication::translate("Widget", "\346\214\201\347\273\255\345\242\236\345\216\213", 0)
         << QApplication::translate("Widget", "\345\256\232\346\227\266\350\256\241\345\216\213", 0)
         << QApplication::translate("Widget", "\345\256\232\346\227\266\345\256\232\345\216\213", 0)
         << QApplication::translate("Widget", "\347\273\225\346\233\262\346\235\276\345\274\233", 0)
         << QApplication::translate("Widget", "\346\270\227\346\260\264\346\274\217\346\260\264", 0)
        );
        pushButton_addMethod->setText(QApplication::translate("Widget", "\346\226\260\345\242\236", 0));
        pushButton_delMethod->setText(QApplication::translate("Widget", "\345\210\240\351\231\244", 0));
        pushButton_modifyMethod->setText(QApplication::translate("Widget", "\344\277\256\346\224\271", 0));
        comboBox_unit->clear();
        comboBox_unit->insertItems(0, QStringList()
         << QApplication::translate("Widget", "Pa(\345\270\225)", 0)
         << QApplication::translate("Widget", "kPa(\345\215\203\345\270\225)", 0)
         << QApplication::translate("Widget", "mBar(\346\257\253\345\267\264)", 0)
         << QApplication::translate("Widget", "mmH2O(\346\257\253\347\261\263\346\260\264\346\237\261)", 0)
        );
        pushButton_saveMethod->setText(QString());
        label_testMethodMessage->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("Widget", "Tab 2", 0));
        label_reportQuery->setText(QApplication::translate("Widget", "\346\265\213\350\257\225\347\273\223\346\236\234", 0));
        label_endDate->setText(QApplication::translate("Widget", "\347\273\223\346\235\237\346\227\245\346\234\237\357\274\232", 0));
        label_startDate->setText(QApplication::translate("Widget", "\350\265\267\345\247\213\346\227\245\346\234\237\357\274\232", 0));
        label_testMethod->setText(QApplication::translate("Widget", "\346\265\213\350\257\225\346\226\271\346\241\210\357\274\232", 0));
        label_methodName->setText(QApplication::translate("Widget", "\346\226\271\346\263\225\345\220\215\347\247\260\357\274\232", 0));
        label_userName->setText(QApplication::translate("Widget", "\347\224\250\346\210\267\357\274\232", 0));
        comboBox_queryTestMethod->clear();
        comboBox_queryTestMethod->insertItems(0, QStringList()
         << QApplication::translate("Widget", "\350\257\267\351\200\211\346\213\251\346\265\213\350\257\225\346\226\271\346\241\210", 0)
         << QApplication::translate("Widget", "\346\214\201\347\273\255\345\242\236\345\216\213", 0)
         << QApplication::translate("Widget", "\345\256\232\346\227\266\350\256\241\345\216\213", 0)
         << QApplication::translate("Widget", "\345\256\232\346\227\266\345\256\232\345\216\213", 0)
         << QApplication::translate("Widget", "\347\273\225\346\233\262\346\235\276\345\274\233", 0)
         << QApplication::translate("Widget", "\346\270\227\346\260\264\346\274\217\346\260\264", 0)
        );
        pushButton_query->setText(QApplication::translate("Widget", "\345\216\206\345\217\262\346\225\260\346\215\256\346\237\245\350\257\242", 0));
        pushButton_delReport->setText(QApplication::translate("Widget", "\345\210\240\351\231\244", 0));
        pushButton_genReport->setText(QApplication::translate("Widget", "\347\224\237\346\210\220\346\212\245\345\221\212", 0));
        label_queryMessage->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("Widget", "Tab 3", 0));
        label_accountManagement->setText(QApplication::translate("Widget", "\350\264\246\345\217\267\347\256\241\347\220\206", 0));
        label_accountList->setText(QApplication::translate("Widget", "  \350\264\246\345\217\267\345\210\227\350\241\250", 0));
        label_accountInfo->setText(QApplication::translate("Widget", "  \350\264\246\345\217\267\344\277\241\346\201\257", 0));
        label_accountName->setText(QApplication::translate("Widget", "\347\224\250\346\210\267\345\220\215\357\274\232", 0));
        label_accountPassword->setText(QApplication::translate("Widget", "  \345\257\206\347\240\201\357\274\232", 0));
        label_accountType->setText(QApplication::translate("Widget", "\347\224\250\346\210\267\347\261\273\345\236\213\357\274\232", 0));
        pushButton_newAccount->setText(QApplication::translate("Widget", "\346\226\260\345\242\236", 0));
        pushButton_delAccount->setText(QApplication::translate("Widget", "\345\210\240\351\231\244", 0));
        pushButton_modifyAccount->setText(QApplication::translate("Widget", "\344\277\256\346\224\271", 0));
        label_advance->setText(QApplication::translate("Widget", "\351\253\230\347\272\247\351\200\211\351\241\271", 0));
        label_dropRec->setText(QApplication::translate("Widget", "\346\260\264\346\273\264\350\257\206\345\210\253\357\274\232", 0));
        label_flowInTime->setText(QApplication::translate("Widget", "\350\277\233\346\260\264\346\227\266\351\227\264\357\274\232", 0));
        label_dropArea->setText(QApplication::translate("Widget", "\346\260\264\347\217\240\351\235\242\347\247\257\357\274\232", 0));
        label_sensitivity->setText(QApplication::translate("Widget", "\347\201\265\346\225\217\345\272\246\357\274\232", 0));
        label_ignoreWidth->setText(QApplication::translate("Widget", "\345\277\275\347\225\245\350\276\271\347\274\230\345\256\275\345\272\246\357\274\232", 0));
        label_pressureRange->setText(QApplication::translate("Widget", "\345\216\213\345\212\233\351\207\217\347\250\213\357\274\232", 0));
        label_centerX->setText(QApplication::translate("Widget", "\350\247\206\351\207\216\344\270\255\345\277\203X\357\274\232", 0));
        label_centerY->setText(QApplication::translate("Widget", "\350\247\206\351\207\216\344\270\255\345\277\203Y\357\274\232", 0));
        label_r->setText(QApplication::translate("Widget", "\350\247\206\351\207\216\345\215\212\345\276\204\357\274\232", 0));
        label_pressureCali->setText(QApplication::translate("Widget", "\345\216\213\345\212\233\346\240\207\345\256\232", 0));
        pushButton_pressureCali->setText(QApplication::translate("Widget", "\347\241\256\345\256\232", 0));
        label_actual1->setText(QApplication::translate("Widget", "\345\256\236\351\231\205\345\200\2741\357\274\232", 0));
        label_theory1->setText(QApplication::translate("Widget", "\347\220\206\350\256\272\345\200\2741\357\274\232", 0));
        label_actual2->setText(QApplication::translate("Widget", "\345\256\236\351\231\205\345\200\2742\357\274\232", 0));
        label_actual3->setText(QApplication::translate("Widget", "\345\256\236\351\231\205\345\200\2743\357\274\232", 0));
        label_theory2->setText(QApplication::translate("Widget", "\347\220\206\350\256\272\345\200\2742\357\274\232", 0));
        label_theory3->setText(QApplication::translate("Widget", "\347\220\206\350\256\272\345\200\2743\357\274\232", 0));
        pushButton_saveAccount->setText(QString());
        pushButton_saveParams->setText(QString());
        label_advanceMessage->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("Widget", "Tab 4", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QApplication::translate("Widget", "Tab 5", 0));
        label_6->setText(QString());
        label_bottom->setText(QApplication::translate("Widget", "CopyRight(C) 2015 NingBo Textile Instrument Factory", 0));
    } // retranslateUi

};

namespace Ui {
    class Widget: public Ui_Widget {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_WIDGET_H
